import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Box,
  Container,
  Typography,
} from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";

const faqs = [
  {
    question: "Is this a subscription?",
    answer:
      "No. All plans are one-time purchases with access for the stated duration.",
  },
  {
    question: "Will my workout be personalized?",
    answer:
      "Yes. Every plan is tailored to your goals and reviewed by a coach.",
  },
  {
    question: "Can I upgrade later?",
    answer:
      "Yes. Upgrades are available based on the applicable pricing.",
  },
  {
    question: "Do I need gym equipment?",
    answer:
      "Your programme is designed around the equipment you have available.",
  },
  {
    question: "Is nutrition included?",
    answer:
      "All memberships include AI-powered nutrition guidance.",
  },
  {
    question: "Who reviews my workout programme?",
    answer:
      "Every programme generated by our AI is reviewed by an experienced fitness coach to ensure it aligns with your goals and follows sound training principles.",
  },
  {
    question: "How is GRIND different from other fitness apps?",
    answer:
      "Unlike generic fitness apps, every GRIND programme is AI-generated, reviewed by a human coach, and personalized to your goals, experience, and lifestyle—combining technology with expert oversight.",
  },
];

const MembershipFAQ = () => {
  return (
    <Box
      component="section"
      sx={{
        py: { xs: 7, md: 10 },
      }}
    >
      <Container maxWidth="lg">
        <Typography
          component="h2"
          sx={{
            fontSize: { xs: 38, md: 50 },
            fontWeight: 800,
            lineHeight: 1,
            textTransform: "uppercase",
            mb: 5,
          }}
        >
          Frequently Asked Questions
        </Typography>

        <Box>
          {faqs.map((faq) => (
            <Accordion
              key={faq.question}
              disableGutters
              sx={{
                backgroundColor: "rgba(255,255,255,0.025)",
                color: "text.primary",
                border: "1px solid rgba(255,255,255,0.12)",
                borderRadius: "8px !important",
                mb: 1.5,
                boxShadow: "none",
                "&:before": {
                  display: "none",
                },
              }}
            >
              <AccordionSummary
                expandIcon={
                  <ExpandMoreIcon
                    sx={{
                      color: "text.primary",
                    }}
                  />
                }
                sx={{
                  minHeight: 70,
                  px: 2.5,
                  "& .MuiAccordionSummary-content": {
                    my: 2,
                  },
                }}
              >
                <Typography
                  sx={{
                    fontSize: 14,
                    fontWeight: 700,
                  }}
                >
                  {faq.question}
                </Typography>
              </AccordionSummary>

              <AccordionDetails
                sx={{
                  px: 2.5,
                  pb: 2.5,
                }}
              >
                <Typography
                  sx={{
                    color: "text.secondary",
                    fontSize: 14,
                    lineHeight: 1.7,
                  }}
                >
                  {faq.answer}
                </Typography>
              </AccordionDetails>
            </Accordion>
          ))}
        </Box>
      </Container>
    </Box>
  );
};

export default MembershipFAQ;